# --- KOTLIN ---
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true

# --- GRADLE & PERFORMANCES ---
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

# --- MÉMOIRE (Config 48Go RAM) ---
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=2g
kotlin.daemon.jvmargs=-Xmx12g -XX:+UseParallelGC
kotlin.native.jvmArgs=-Xmx12g -XX:+UseParallelGC

# --- ANDROID ---
android.useAndroidX=true
android.nonTransitiveRClass=true

# --- IOS / KMP ---
kotlin.apple.xcodeCompatibility.nowarn=true
kotlin.native.ignoreDisabledTargets=true
kotlin.native.cacheKind.iosArm64=none
kotlin.native.cacheKind.iosSimulatorArm64=none