platform :ios, '17.0'
use_frameworks!

def shared_pods
  pod 'app', :path => '../shared/app'
end

target 'iosApp' do
  shared_pods
end

target 'CoreUI' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end