package fr.abknative.outgo.wallet.api.model

import fr.abknative.outgo.core.api.EpochMillis
import fr.abknative.outgo.core.api.SyncStatus

/**
 * Represents a financial container, such as a bank account or a physical cash envelope.
 * It serves as the root entity grouping a collection of [Operation]s.
 *
 * @property id The unique identifier (UUID v4) generated by the client.
 * @property name The display name of the wallet (e.g., "Main Account", "Savings").
 * @property createdAt The local timestamp (EpochMillis) indicating when this wallet was initially created.
 * @property updatedAt The local timestamp of the last modification (local or remote).
 * @property deletedAt The timestamp indicating when this wallet was soft-deleted. If null, the wallet is active.
 * @property syncStatus Current synchronization state with the remote server. Determines whether this object needs to be pushed.
 */
data class Wallet(
    val id: String,
    val name: String,

    // Métadonnées Offline-First
    val createdAt: EpochMillis,
    val updatedAt: EpochMillis,
    val deletedAt: EpochMillis? = null,
    val syncStatus: SyncStatus = SyncStatus.PENDING_CREATE
)